### ISSUE TITLE
Use xip.io service for IP addresses

### ISSUE THREAD

**Issue by ygerasimov** [docksal/drupal8#1]
There is xip.io service to map domains to ip addresses automatically (when service is accessible).

So instead of using a host like drupal8.docksal you can have drupal8.192.168.10.10.xip.io and if users have access to service it will map automatically.

**Comment by lmakarov** [comment]
In my experience, xip.io has not been very reliable. It also requires you to be online for the name resolution to work. I'm going to close this for now, since this will not be getting into the mainstream. Thanks for the suggestion though!
