### ISSUE TITLE
Init Documentation

### ISSUE THREAD

**Issue by loopy3025** [docksal/drupal8#15]
Hi! Thanks for developing this useful implementation of Docker. I've gotten one of our most complex Drupal 8 sites up and running on my Mac using this methodology. It works great. The only thing that I'm not sure about is how I should set up my init script. The Drupal 7 one seems to imply everything goes into the one init script. The Drupal 8 one splits the script into two files: "init" and "init-site". Adding my commands to init-site doesn't seem to work for whatever reason - I'm guessing because Docksal isn't declared there. What I did was create a new script called "init-local" and called it with fin init-local from the main init script.  Calling it from the init-site script didn't work because it didn't understand what the "fin" command was.

Is this correct? I'm concerned a future fin update will overwrite the line I added to the init file. I guess if it's working, then that's great, but I want to make sure it's the correct way to go about doing it so we're compliant with standards going forward.

Here's the code I'm executing in init-local:

```
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
fin stop
fin start
cd ${DOCROOT_PATH}
echo "Dropping database..."
fin drush sql-drop -y
echo "Importing database from /docroot/db/db.sql";
fin sqli ./db/db.sql --db=default
fin drush en stage_file_proxy -y
fin drush cr
```

And here's the line I added to init:

```
# run the local settings script
fin init-local
```

Thanks, in advance, for your help.
=Adam=

**Comment by sean-e-dietrich** [comment]
@loopy3025 is that your full `init-local` script? I'm asking because have you put the #! as the first line?

```
#!/usr/bin/env bash
```

**Comment by achekulaev** [comment]
@loopy3025 `fin update` will not overwrite any files under `commands` folder.

**Comment by esteinborn** [comment]
@loopy3025 Take a look at the init-site file, as mentioned above, and add the lines it has at the top:

```
#!/usr/bin/env bash

#: exec_target = cli
```

Also, remove all the references to `fin` in your `init-local` script because you will only ever be calling it from `init` by calling:
```
fin init-local
```
Which, prepends fin to all previous commands. 

So your new output should be:
```
#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-local (should not be run by itself)

# Abort if anything fails
set -e

SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

existing_site_install ()
{
  cd ${DOCROOT_PATH}
  echo "Dropping database..."
  drush sql-drop -y
  echo "Importing database from /docroot/db/db.sql";
  sqli ./db/db.sql --db=default
  drush en stage_file_proxy -y
  drush cr
}

time existing_site_install

```

**Comment by achekulaev** [comment]
@loopy3025 can we close this one?

**Comment by lmakarov** [comment]
@achekulaev let's keep this open. Init script best practices/tutorial is something we should have.

I started working on a blog post on blog.docksal.io a while ago, but never got that one finished.

**Comment by shelane** [comment]
https://blog.docksal.io/writing-fin-init-and-other-docksal-custom-commands-dc103b2747cd

The blog post was finished and published.
