### ISSUE TITLE
Getting error ERROR: Volume docksal_ssh_agent declared as external, but could not be found.

### ISSUE THREAD

**Issue by stephencross** [docksal/drupal8#17]
I've followed the instructions, and I'm getting the following error.  

ERROR: Volume docksal_ssh_agent declared as external, but could not be found. Please create the volume manually using `docker volume create --name=docksal_ssh_agent` and try again.

I ran docker volume create --name=docksal_ssh_agent, as recommended, but  still get the error

Any advice?

**Comment by achekulaev** [comment]
No idea. More info needed.

**Comment by lmakarov** [comment]
This most likely indicated that the `docksal-ssh-agent` container/service was never started.

As @achekulaev mentioned, we need the details from `fin sysinfo` and `fin config` (as outlined in the new issue template).

**Comment by lmakarov** [comment]
Closing for lack of feedback. Feel free to reopen.
