### ISSUE TITLE
Support other installation systems

### ISSUE THREAD

**Issue by ikit-claw** [docksal/drupal8#20]
Any chance this is going to consider other Linux OS? I am looking for a way to setup on Arch Linux

**Comment by achekulaev** [comment]
This questions better be posted in https://github.com/docksal/docksal.

You can create a ticket to request support for Arch Linux, but it's going to be pretty low in the priority list.

Arch linux should work mostly fine actually. DNS might now work as expected. We do it via `/etc/network/interfaces/`.

```
	up   ip addr add ${DOCKSAL_DEFAULT_SUBNET} dev lo label lo:docksal
	down ip addr del ${DOCKSAL_DEFAULT_SUBNET} dev lo label lo:docksal
	dns-nameservers ${DOCKSAL_DEFAULT_IP}
```

But if you could figure out a proper way to configure DNS on Arch we could append it's support.

**Comment by ikit-claw** [comment]
@achekulaev do you have a curl installation option? Currently, it just goes not ubuntu sorry. Stops installation.

**Comment by achekulaev** [comment]
Oh sorry! I thought we were talking Mint, my bad. Arch is not even dpkg based. Yes it's hella lot of work to support it.

**Comment by ikit-claw** [comment]
That is a shame guess I will stick with DDEV thanks for getting back to me.
