### ISSUE TITLE
DOCROOT variable not available in custom command

### ISSUE THREAD

**Issue by opdavies** [docksal/drupal8#22]
If `exec_target` is set to `cli`, the `$DOCROOT` variable is not available.

I've tested it with a super simple command:

```bash
#!/usr/bin/env bash

#: exec_target = cli

echo $DOCROOT
```

This results in no output.

However, just this does:

```bash
#!/usr/bin/env bash

echo $DOCROOT
```

`DOCROOT` is defined in my `.docksal/docksal.env` file. Other variables such as `$PROJECT_ROOT` are fine.

**Comment by achekulaev** [comment]
Closing this one in favor of https://github.com/docksal/docksal/issues/515
