### ISSUE TITLE
Why drupal on the repo and not go for a drupal-composer project?

### ISSUE THREAD

**Issue by hanoii** [docksal/drupal8#23]
I pretty much use  https://github.com/drupal-composer/drupal-project on every drupal project, and platform.sh (just where I mostly do my work) is very much into this approach.

I just wonder why you went with this example and if you think composer managed would make it more prone to issues/less performant?

**Comment by achekulaev** [comment]
This example is much faster to install than composer.

But you use can use composer as well. I wrote a blog post recently about [creating Drupal 8 project from scratch using Composer pre-installed in Docksal cli](https://blog.docksal.io/creating-drupal-8-project-from-scratch-using-pre-installed-composer-in-docksal-cli-bfe49b0042e2).

@lmakarov has a [plan](https://github.com/docksal/docksal/issues/174) for composer-manager repo as well.

**Comment by lmakarov** [comment]
We now have a Drupal8 boilerplate repo created using [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project ):

https://github.com/docksal/boilerplate-drupal8-composer
