### ISSUE TITLE
Fix sendmail_path override for drush site-install in the init script

### ISSUE THREAD

**Issue by lmakarov** [docksal/drupal8#25]
`fin init` does not complete due to `drush si` exiting with an error:

```
error sending mail
2018/07/04 02:22:35 dial tcp: lookup mail on 127.0.0.11:53: no such host
```

Apparently, the following workaround no longer works: https://github.com/docksal/drupal8/commit/9eca2bc54e052a648e8667ed53b0f595a30d63ba

Here's the first failing build on Travis: https://travis-ci.org/docksal/drupal8/builds/400486545

**Comment by lmakarov** [comment]
This is weird... Here are two consecutive builds on master:

https://travis-ci.org/docksal/drupal8/builds/400486545 - failed
https://travis-ci.org/docksal/drupal8/builds/400636740 - passed

There were no changes to the init script in-between, just the Drupal core updated from 8.5.4 to 8.5.5

Looks like this issue was "magically" resolved by just upgrading Drupal.

**Comment by achekulaev** [comment]
Well, that was easy!
