### ISSUE TITLE
fin init with no errors but "This site can’t be reached"

### ISSUE THREAD

**Issue by GiorgosK** [docksal/drupal8#6]
how can I debug this ?
here is the output of the fin init 

` WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: No swap limit support
 Step 1  Initializing local project configuration...
/home/giorgos/websites/drupal8/docroot/sites/default/settings.local.php already in place.
 Step 2  Recreating services...
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: No swap limit support
Removing containers...
Removing drupal8_web_1 ... done
Removing drupal8_cli_1 ... done
Removing drupal8_db_1 ... done
Removing network drupal8_default
Removing volume drupal8_project_root
Volume docksal_ssh_agent is external, skipping
Removing volume drupal8_host_home
Starting services...
Creating network "drupal8_default" with the default driver
Creating volume "drupal8_project_root" with local driver
Creating volume "drupal8_host_home" with local driver
Creating drupal8_cli_1
Creating drupal8_db_1
Creating drupal8_web_1
Waiting 10s for MySQL to initialize...
 Step 3  Installing site...
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: No swap limit support
You are about to DROP all tables in your 'default' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                                                          [ok]
Installation complete.  User name: admin  User password: JxX6zNJKzJ                                                                                                                                   [ok]
Congratulations, you installed Drupal!                                                                                                                                                                [status]

real	0m48.688s
user	0m0.412s
sys	0m0.064s
 DONE!  Open http://drupal8.docksal in your browser to verify the setup.
`

**Comment by lmakarov** [comment]
@GiorgosK please post the output from `fin sysinfo` here.

**Comment by lmakarov** [comment]
It's very likely that the DNS resolution is not working properly.
What's the output from `nslookup drupal8.docksal 192.168.64.100`?

Try adding `192.168.64.100 drupal8.docksal` to you hosts file and see if that helps.

**Comment by GiorgosK** [comment]
$fin sysinfo
> ███  OS & BASICS
Linux glaptop 4.9.0-040900-generic #201612111631 SMP Sun Dec 11 21:33:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
fin version: 1.0.2
Mode:  Native / Docker for Mac/Windows
███  DOCKER
DOCKER_HOST:	

> Docker:
 Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

> Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
███  DOCKER COMPOSE
Docker Compose: docker-compose version 1.10.1, build b252738
docker-py version: 2.0.2
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: No swap limit support
███  DOCKER: IMAGES
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
giorgosk/catnip           latest              9b4cf50a5d85        12 hours ago        697 MB
docksal/web               1.0-apache2.2       a9c03f8a5f0f        2 weeks ago         188 MB
docksal/db                1.0-mysql-5.5       9fb8c0aed5fc        2 weeks ago         255 MB
docksal/cli               1.0-php7            5bc490ae4d93        2 weeks ago         746 MB
python                    3-onbuild           ba9bca863b96        2 weeks ago         687 MB
busybox                   latest              7968321274dc        3 weeks ago         1.11 MB
hello-world               latest              c54a2cc56cbb        7 months ago        1.85 kB
prakhar1989/static-site   latest              f01030e1dcf3        13 months ago       134 MB
███  DOCKER: CONTAINERS
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                     NAMES
81b02725d7db        docksal/web:1.0-apache2.2   "/opt/startup.sh a..."   10 hours ago        Up 10 hours         80/tcp, 443/tcp           drupal8_web_1
26f6953e49b3        docksal/db:1.0-mysql-5.5    "/entrypoint.sh my..."   10 hours ago        Up 10 hours         0.0.0.0:32770->3306/tcp   drupal8_db_1
61835ac5f684        docksal/cli:1.0-php7        "/opt/startup.sh g..."   10 hours ago        Up 10 hours         22/tcp, 9000/tcp          drupal8_cli_1
███  VIRTUALBOX
5.1.12r112440
███  NETWORK INTERFACES
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.44.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

> Name:
            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.33.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

$nslookup drupal8.docksal 192.168.64.100
> ;; connection timed out; no servers could be reached

I already added `192.168.64.100 drupal8.docksal`
to /etc/hosts and did a restart just in case but it did not work 

Also nmap shows there is an association of ip/domain

$ nmap -sP 192.168.64.100
> Starting  Nmap 7.01 ( https://nmap.org ) at 2017-02-04 07:41 EET
Nmap scan report for drupal8.docksal (192.168.64.100)
Host is up (0.000077s latency).
Nmap done: 1 IP address (1 host up) scanned in 0.00 seconds

and I can actually ping the ip

> $ ping 192.168.64.100
PING 192.168.64.100 (192.168.64.100) 56(84) bytes of data.
64 bytes from 192.168.64.100: icmp_seq=1 ttl=64 time=0.075 ms

maybe its listening to a specific port ?
before trying docksal I had installed kalabox.io which is a docker solution but I have uninstalled is there maybe a connection ? 
but I am able to run all other docker images ...

**Comment by lmakarov** [comment]
I see you have newer versions of docker and docker-compose installed than what we currently support in Docksal.
Please run `fin update` and post the output. This should install/downgrade to the supported versions. It will also reset Docksal system services (vhost-proxy, dns and ssh-agent) - looks like you don't have those running at all.

**Comment by GiorgosK** [comment]
before I downgrade please tell me what versions of docker/docker-compose does docksal recommend/install ? 

I am worried I might not be able to run other stuff that I created with docker / docker-compose already !!

**Comment by lmakarov** [comment]
```
REQUIREMENTS_DOCKER='1.12.6'
REQUIREMENTS_DOCKER_COMPOSE='1.9.0'
REQUIREMENTS_DOCKER_MACHINE='0.8.2'
```

**Comment by lmakarov** [comment]
In the latest Docksal release we now use docker 1.13.1
https://github.com/docksal/docksal/releases/tag/v1.1.0
