### ISSUE TITLE
ERROR Cannot start service db: no such file or directory

### ISSUE THREAD

**Issue by GhostInTheMachinesAtTSBVI** [docksal/drupal8#7]
I followed the following instructions to run the sample Drupal8 setup for Docksal:

https://github.com/docksal/drupal8

But when I ran fin init, the following errors were displayed:

ERROR: for db  Cannot start service db: no such file or directory

ERROR: for cli  Cannot create container for service cli: no such file or directory
ERROR: Encountered errors while bringing up the project.

I am using Docker for Mac and I have some custom mapping in my /etc/hosts. I read a similar post where there were problems with this situation but it did not elaborate on how it could be resolved.

Should be using some other type of Docker installation and can I not use custom /etc/hosts entries?

I ran fin init a second time and received the same errors.

**Comment by GhostInTheMachinesAtTSBVI** [comment]
While I was waiting for a reply I ran fin init again today and it looks like it did some kind of git pull and then worked with only a minor error message about not being able to send an email:

Unable to send email. Contact the site administrator if the problem persists.        [error]

I guess the issue is resolved for now so I will close this issue

**Comment by esteinborn** [comment]
probably due to the Amazon outage yesterday.
