### ISSUE TITLE
Add a default --root for fin drupal

### ISSUE THREAD

**Issue by asherry** [docksal/drupal8#9]
It's not an issue, I have more of a question. I want to customize the DOCROOT to be `build/html`, but weirdly if it's two levels deep then it won't auto find drupal console in build/html/vendors. 

I actually don't even want the drupal console and vendors directory in the drupal root anyway because in particular config it's in the project root. What I'd like to do is instead just tell `fin` that every time you call `fin drupal`, give it the parameter of `fin drupal --root=/var/www/build/html`, that seems to work just fine.

Is this possible?

**Comment by achekulaev** [comment]
Hi! 
Thank you for well described question.

For security reasons it's not possible to override **inbuilt** commands and `fin drupal` is an inbuilt command at the moment.

However you could [create your own command](http://docksal.readthedocs.io/en/master/fin/custom-commands/) that would run 
```
fin drupal --root=/var/www/build/html "$@"
```

**Comment by asherry** [comment]
Yeah you're totally right, I guess I was over-thinking it. I'll just create a new custom command then, thanks so much for your work.
